version: '3.8'
services:
  scrapy:
    build: ./scraper
    container_name: scrapy
    user: "1000:1000"
    volumes:
      - ./scraper:/scraper
    depends_on:
      - chromedriver
      - pgdb
      - redis


  chromedriver:
    image: selenium/standalone-chrome
    container_name: chromedriver
    ports: 
      - "4444:4444"
    shm_size: '512M'  
    tmpfs:
      - /dev/shm

  pgdb:
    image: postgres:latest
    container_name: pgdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - pgdata:/var/lib/postgresql/data/
    
      
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6380:6380'
    command: redis-server --port 6380

volumes:
  pgdata:
